### ISSUE TITLE
reading Java Home gives issue

### ISSUE THREAD

**Issue by NayaneshGupte** [tiwiz/RxAndroidCrunch#1]
after I commented following code in gradle it worked for me

String getJavaHome(String version)
{
    def stdout = new ByteArrayOutputStream()
    exec {
        commandLine "/usr/libexec/java_home", "-v", version
        standardOutput = stdout;
    }
    return stdout.toString().trim()
}

retrolambda {
    jdk System.getenv('JAVA8_HOME') ?: getJavaHome("1.8")
    oldJdk System.getenv('JAVA7_HOME') ?: getJavaHome("1.7")
}

**Comment by tiwiz** [comment]
Hello!

Based on your OS and configuration, that part is needed or not. On both my Mac is needed, are you on Windows?

**Comment by NayaneshGupte** [comment]
I'm on MAC as well but though it solved my compilation issue, I'm still getting this issue:

Error:Execution failed for task ':app:compileDebugJavaWithJavac'.

> When running gradle with java 5, 6 or 7, you must set the path to jdk8, either with property retrolambda.jdk or environment variable JAVA8_HOME

what am I missing here ?

**Comment by NayaneshGupte** [comment]
fixed after installing java 8.

**Comment by tiwiz** [comment]
I was writing that :-D

**Comment by NayaneshGupte** [comment]
Thanks !
